import gsap from "gsap";
import Head from "next/head";
import { useEffect, useRef } from "react";
import {ScrollTrigger} from "gsap/dist/ScrollTrigger";

import Banner from "../../../components/sections/showcase/templates/banner/Banner";
export default function Template () {

  const mainRef = useRef()

  const data = {
    template_name: "RentCar",
    template_owner_target: "Location de véhicule - Concessionnaire - Garagiste - Transporteur",
    template_banner_img : "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80"
  }

  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger)

    const sections = gsap.utils.toArray("section");
    let maxWidth = 0;
    const getMaxWidth = () => {
      maxWidth = 0;
      sections.forEach((section) => {
        maxWidth += section.offsetWidth;
      });
    };
    getMaxWidth();
    ScrollTrigger.addEventListener("refreshInit", getMaxWidth);

    gsap.to(sections, {
  x: () => `-${maxWidth - window.innerWidth}`,
  ease: "none",
  scrollTrigger: {
    trigger: mainRef.current,
    pin: true,
    scrub: true,
    end: () => `+=${maxWidth}`,
    invalidateOnRefresh: true
  }
});

  }, [])

  return (
    <div>
      <Head>
        <title>Modular Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main ref={mainRef}>
        <Banner title={data.template_name} background={data.template_banner_img} label={data.template_owner_target}/>
        <section>
          A
        </section>
        {/* <section>
          B
        </section> */}
        
      </main>
    </div>
  );
}