import Head from 'next/head'
import Banner from '../components/sections/home/banner/Banner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Modular Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner/>
      </main>
    </div>
  )
}
