import Head from "next/head";
import Arguments from "../components/sections/home/args/Arguments";
import Banner from "../components/sections/home/banner/Banner";
import PageContent from "../components/sections/home/offer/Offer";
import Avis from "../components/sections/home/avis/Avis";
import Starterz from "../components/global/Starterz/Starterz";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Modular Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <Arguments />
        {pageContent.map((el, i ) => {
          return <PageContent content={el} i={i}/>
        })}
        <Starterz/>
        <Avis/>
      </main>
    </div>
  );
}

export const pageContent = [
  {
    icon : "/assets/illustration/cible.png",
    label: "Des offres adaptées à tous",
    para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed varius ligula nec augue aliquam, non interdum ante rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    button: {
      link: "/offres",
      text: "Nos offres",
    },
    img : [
      
      {
        src: "/assets/illustration/bag.svg",
        leftImg: "55%",
      },
      {
        src: "/assets/illustration/persowall.png",
        leftImg: "68.5%",
        width: "40%"
      },
    ],
    left: "15%",
    
  },
  {
    icon : "/assets/illustration/crayon.png",
    label: "Existant ou sur mesure, vous avez l'ambarra du choix !",
    para: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed varius ligula nec augue aliquam, non interdum ante rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    button: {
      link: "/showcase",
      text: "Consulter",
    },
    left: "55%",
    img : [
      {
        src: "/assets/illustration/custom.svg",
        leftImg: "0%",
        width: "50%"
      },
      {
        src: "/assets/illustration/bighandcustom.svg",
        leftImg: "15%",
      },
    ]
  },
];
