import Head from "next/head";
import Banner from "../../components/sections/showcase/theme/banner/Banner";
import Topic from "../../components/sections/showcase/theme/topic/Topic";

export default function Home() {

  const content = [
    {
      label : "Créer une présence sur internet rapidement et simplement",
      category : "Starterz",
      targetWords: ["Créer", "rapidement"],
      ipadImg: "https://downloadpsd.cc/wp-content/uploads/image-12682.jpg",
      theme: {
        background: "var(--basic-purple)",
        color: "var(--font-color)"
      }
    },
    {
      label : "Mettez en avant votre activité grace a votre nouvelle vitrine sur le web !",
      category : "Vitrine",
      targetWords: ["votre activité", "vitrine"],
      ipadImg: "https://images-platform.99static.com//cboee49j3q9KQBMjj4cTKkRY-78=/0x0:1920x1920/fit-in/500x500/99designs-contests-attachments/80/80081/attachment_80081342",
      theme: {
        background: "var(--pink)",
        color: "var(--dark-purple)"
      }
    },
    {
      label : "Permettez a votre clientèle de commander en ligne simplement",
      category : "e-commerce",
      targetWords: ["vos futur", "confiance"],
      ipadImg: "https://images-platform.99static.com//ZUU0DJkgfiPJzVKTgSEaii6H9G8=/5x0:1705x1700/fit-in/590x590/99designs-contests-attachments/111/111213/attachment_111213383",
      theme: {
        background: "var(--deep-purple)",
        color: "var(--font-color)"
      }
    },
    {
      label : "Association, institution, faites ressortir ce pour quoi vous vous battez",
      category : "Institutionnel",
      targetWords: ["vos futur", "confiance"],
      ipadImg: "https://blog.hubspot.com/hs-fs/hubfs/Sparkling%20theme%20demo.jpg?width=599&name=Sparkling%20theme%20demo.jpg",
      theme: {
        background: "#F2F2F2",
        color: "var(--dark-purple)"
      }
    },
  ]

  return (
    <div>
      <Head>
        <title>Modular Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Banner/>
          {content.map((el, i) => {
            return <Topic data={el}/>
          })}
      </main>
    </div>
  );
}