import Head from "next/head";
import Banner from "../../components/sections/showcase/theme/banner/Banner";
import Topic from "../../components/sections/showcase/theme/topic/Topic";

export default function Home() {

  const content = [
    {
      label : "Decriver pourquoi vos futur adhérents doivent vous faire confiance",
      category : "sport",
      targetWords: ["vos futur", "confiance"],
      theme: {
        background: "var(--pink)",
        color: "var(--dark-purple)"
      }
    },
  ]

  return (
    <div>
      <Head>
        <title>Modular Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Banner/>
          {content.map((el, i) => {
            return <Topic data={el}/>
          })}
      </main>
    </div>
  );
}